feat(registry): first pass at code and tests
devtooligan/yield_mentorship pull request #1
Opened 2021-08-13 02:09 UTC by Eihcir0

https://github.com/albertocuestacanada/solidity-mentorship/issues/1

2021-08-13 08:24 UTC, albertocuestacanada commented on contracts/Registry.sol
> +
Natspec, please, at least a @dev line.

2021-08-13 08:26 UTC, albertocuestacanada commented on contracts/Registry.sol
> +        claimedNames[_name] = msg.sender;
At the end of each function that modifies the state, you should emit an event if the final value of the modified variables. Events are vital for frontend integration.

2021-08-13 08:29 UTC, albertocuestacanada commented on test/registry/Registry.ts
> +
You can nest a `describe` block inside `#claimName()`, and in the `beforeEach` block of that nested `describe`, you put the function that you just tested to work: `registry.claimName(name)`.

That way you follow a pattern:
 - You are at state 0
 - Test all the things that should revert
 - Test one thing that should work
 - Nest a describe, put the thing that works in the beforeEach, you are at state 1.

You will end with a kind of state tree, testing all the possible reverts, all the possible states, and all the possible successful functions.

2021-08-13 08:31 UTC, albertocuestacanada requested changes
Love it. The simpler is always the better. No place for bugs to hide, and minimal gas cost. Some minimal changes requested (comments, events) and a recommendation on writing better tests.

2021-08-13 08:33 UTC, albertocuestacanada requested changes
Love it. The simpler is always the better. No place for bugs to hide, and minimal gas cost. Some minimal changes requested (comments, events) and a recommendation on writing better tests.

2021-08-14 23:47 UTC, Eihcir0 commented on contracts/Registry.sol
> +/// @title Name Registry
These natspecs seem a little overkill.  In the past I try to make my code as self-documenting as possible and only use comments to help clear up those "wtf" moments.

However, I realize there is a strong use case for comments on smart contracts, I'm sure I will figure out what's important over time and by reviewing smart contracts of others.

2021-08-15 02:08 UTC, Eihcir0 commented
[contract deployed and verified on Kovan](https://kovan.etherscan.io/address/0x2F1C961F580805F5F1FcB7F6981d2d3674325C0d#code)

2021-08-15 11:59 UTC, albertocuestacanada commented on contracts/Registry.sol
> +/// @title Name Registry
Agree, I usually have a single @dev short paragraph. If I need @param or @return natspec that's actually a sign that there is something wrong with the design. Sometimes I add a @notice when there is something important to say (again, a sign that something is wrong)

Then, I tend to add in-line comments, as minimal code can't always be self-evident, or when something was considered that led to a particular design choice. Also when breaking a longer function into steps.

2021-08-15 12:03 UTC, albertocuestacanada approved these changes
Great job. I like that you went straight and to the point. I think you'll sail through the next couple of issues.

2021-08-16 00:13 UTC, merged