feat(vault1): code and tests for issue #2 - Vault
devtooligan/yield_mentorship pull request #2
Opened 2021-08-18 00:34 UTC by Eihcir0

2021-08-18 00:34 UTC, Eihcir0 commented on contracts/Vault.sol
> +    // Is there any security risk by making this public? I guess they'd see it on chain anyway
?

2021-08-18 00:34 UTC, Eihcir0 commented on test/vault/Vault.ts
> +      // ^^ I couldn't figure out how to access the ERC-20 generated error message here
?

2021-08-18 04:10 UTC, sblOWPCKCR commented on test/vault/Vault.ts
> +      // ^^ I couldn't figure out how to access the ERC-20 generated error message here
wouldn't just `to.be.revertedWith('ERC20: Insufficient balance')` work? I do have this in my code:
```
        await expect(this.gvault
          .connect(this.signers.user2)
          .withdraw(1))
          .to.be.revertedWith("ERC20: Insufficient balance");
```

2021-08-18 06:46 UTC, albertocuestacanada commented on contracts/Vault.sol
> +    // Is there any security risk by making this public? I guess they'd see it on chain anyway
No security risk whatsoever. I don't use private or internal variables very often. I can't really think what to use them for.

2021-08-18 06:47 UTC, albertocuestacanada commented on test/vault/Vault.ts
> +      // ^^ I couldn't figure out how to access the ERC-20 generated error message here
This :point_up:

2021-08-18 06:54 UTC, albertocuestacanada requested changes
This is an easy one, but still gives you the opportunity to learn about gas use (calls to other contracts are expensive) and about reentrancy attacks.

2021-08-18 06:54 UTC, albertocuestacanada commented on contracts/Vault.sol
> +        balances[msg.sender] += amount;
You should follow the [checks - effects - interactions](https://fravoll.github.io/solidity-patterns/checks_effects_interactions.html) pattern here, otherwise you open yourself to a [reentrancy attack](https://quantstamp.com/blog/what-is-a-re-entrancy-attack).

2021-08-18 06:54 UTC, albertocuestacanada commented on contracts/Vault.sol
> +        require(_token.allowance(msg.sender, address(this)) >= amount, "Approve deposit first");
You don't need to check the `allowance` yourself, `transferFrom` will revert if the allowance is not there.

It might do for better UX to have custom error messages (I know I've struggled sometimes to find out an approval was missing), but each call to another contract is quite expensive in gas terms.

2021-08-19 00:11 UTC, Eihcir0 commented on test/vault/Vault.ts
> +      // ^^ I couldn't figure out how to access the ERC-20 generated error message here
hmm, I'm not sure what was going on before but now it's working.

2021-08-19 00:33 UTC, Eihcir0 commented on contracts/Vault.sol
> +        balances[msg.sender] += amount;
cool.  I did originally read some about reentrancy attacks because my linter yelled at me in the withdraw() method below.   Because it didn't yell at me here I incorrectly assumed that it was ok (if someone wants to make multiple deposits to us, then go ahead!) but I see now that this is an antipattern and we want to save any calls to external contracts to the end.  I also read more about[ general security considerations](https://docs.soliditylang.org/en/v0.4.21/security-considerations.html#use-the-checks-effects-interactions-pattern).

2021-08-19 00:34 UTC, Eihcir0 commented on contracts/Vault.sol
> +        balances[msg.sender] += amount;
I'm guessing that even though we say we should save external callls until the very end, it's still ok to emit events after the external call because it's not really a security concern and wouldn't make sense also if we emitted the event before the transfer.

2021-08-19 00:54 UTC, Eihcir0 commented on contracts/Vault.sol
> +        balances[msg.sender] += amount;
I also played around with the gas-reporter, very interesting. It appears deposit() is the most expensive

2021-08-19 00:55 UTC, merged