feat(vault4): code and tests
devtooligan/yield_mentorship pull request #6
Opened 2021-09-07 03:48 UTC by Eihcir0

Exercise5: Collateralized Vault
A vault which accepts eth deposits and can lend dai.  Includes "liquidate" function as well as using a mock price feed aggregator based on Chainlink.

I deployed the contracts to Kovan but ran into problems verifying -- just hangs here:

```
$ yarn hardhat verify --network kovan 0x3F628796dBA8269E484d34Bd4a07c967b786069A 0x5f25FEF2a2Fb696c4e24ac6a5147D2b454A1f5f6 0x8428d2B425B7A0D008B2576d39d72971c2d5aC1c
Nothing to compile
No need to generate any newer typings.
Compiling 1 file with 0.8.6
Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> contracts/Dai.sol

Successfully submitted source code for contract
contracts/Vault4.sol:Vault4 at 0x3F628796dBA8269E484d34Bd4a07c967b786069A
for verification on Etherscan. Waiting for verification result...
```

Tests complete:
```
  Vault4 Unit tests
    without deposits or loans
      ✓ #withdraw() should not be able to withdraw without a deposit
      ✓ #borrow() should not be able to borrow without a deposit
      ✓ #liquidate() should not be able to liquidate without a deposit
      ✓ #deposit() should allow deposits from one or more users (64ms)
    with deposits
      ✓ #withdraw() should not be able to withdraw more than the deposit
      ✓ #borrow() should not be able to borrow more than the deposit
      ✓ #deposit() should allow additional deposits
      ✓ #withdraw() should be able to withdraw up to the deposited amount (222ms)
      ✓ #borrow() should be able to borrow up to the deposited amount at current exchange rate (77ms)
      with loans
        ✓ #withdraw() should not be able to withdraw deposits being used as collateral
        ✓ #borrow() should not be able to borrow beyond available collateral (39ms)
        ✓ #liquidate() should not be able to liquidate safe loans
        ✓ #repay() should not be able to repay more than the borrowed amount
        ✓ #repay() should be able to repay up to the borrowed amount (179ms)
        ✓ #liquidate() should be able to liquidate underwater loans (126ms)
        ✓ #withdraw() should be able to withdraw additional eth if ltv drops (93ms)
        ✓ #borrow() should be able to borrow additional eth if ltv drops (41ms)

  17 passing (3s)
```

2021-09-07 03:49 UTC, Eihcir0 commented on contracts/Dai.sol
> +/**
copy pasta of official dai contract with some minor alterations -- namely removing assembly logging logic

2021-09-08 04:49 UTC, alcueca requested changes
Great job. You have a few extra require, and can gas golf a bit, but those are minor things. The price from Chainlink is the reverse of what you think. I made the same mistake for Yield v2 and only figured it out very recently.

2021-09-08 04:49 UTC, alcueca commented on contracts/Vault4.sol
> +        require(_deposit > 0, "Insufficient balance");
I think that you can remove this check, since you check this later: 
```require((_depositDaiValue - loans[msg.sender]) >= _withdrawDaiValue, "Insufficient balance");```

2021-09-08 04:49 UTC, alcueca commented on contracts/Vault4.sol
> +        deposits[msg.sender] -= _ethWad;
This equals `deposits[msg.sender] = deposits[msg.sender] - ethWad`, and you read `deposits[msg.sender]` at L55.

You would use less gas with `deposits[msg.sender] = _deposit - ethWad`

2021-09-08 04:49 UTC, alcueca commented on contracts/Vault4.sol
> +        require(_depositEthValue > 0, "Insufficient collateral1");
You check already in L72

2021-09-08 04:49 UTC, alcueca commented on contracts/Vault4.sol
> +        token.push(msg.sender, _daiWad);
I'm not a fan of `push` and `pull` in Dai.sol, having the IERC20 functions that do the same. I like the names better than `transfer` and `transferFrom`, but non-standard function names harm readability.

2021-09-08 04:49 UTC, alcueca commented on contracts/Vault4.sol
> +        require(_daiWad <= loans[msg.sender], "Amount > loaned");
If you have this `require`, the next line can be in an `unchecked` block.

2021-09-08 04:49 UTC, alcueca commented on contracts/Vault4.sol
> +        require(_depositEth > 0, "No deposit");
I think that this `require` and the next can be safely removed.

2021-09-08 04:49 UTC, alcueca commented on contracts/Vault4.sol
> +        _resultDai = _ethValue * _currentRate;
Play a bit with the aggregator prices in Etherscan, and you'll find that you have this reverted. The Chainlink DAI/ETH rate is how much ETH wei is one Dai token worth.

Instead of something like 3468 380000 000000 000000, it has 290 285977 199063

You have:
```
ethAmount = daiAmount * rate
daiAmount = ethAmount / rate
```
Only these are fixed point operations, and `rate` has 18 decimals as per the chainlink docs, so:
```
ethAmount = daiAmount * rate / 1e18
daiAmount = ethAmount * 1e18 / rate
```

2021-09-08 05:53 UTC, Eihcir0 commented on contracts/Vault4.sol
> +        require(_deposit > 0, "Insufficient balance");
I wasn't sure if maybe we save on gas by not calling applyExchangeRate if they don't even have any deposits?

2021-09-08 05:53 UTC, Eihcir0 commented on contracts/Vault4.sol
> +        _resultDai = _ethValue * _currentRate;
Ok got it.  I'll play around with it and then fix these

2021-09-08 05:55 UTC, Eihcir0 commented on contracts/Vault4.sol
> +        deposits[msg.sender] -= _ethWad;
good catch

2021-09-08 05:55 UTC, Eihcir0 commented on contracts/Vault4.sol
> +        require(_depositEthValue > 0, "Insufficient collateral1");
same comment as above.  I did think about this.  LiWouldnt we not want to make a call to the price aggregator contract if we didn't have to?

2021-09-08 05:56 UTC, Eihcir0 commented on contracts/Vault4.sol
> +        token.push(msg.sender, _daiWad);
ok will change it back, lol I saw those on the Dai and decided to play with them

2021-09-08 05:56 UTC, Eihcir0 commented on contracts/Vault4.sol
> +        require(_daiWad <= loans[msg.sender], "Amount > loaned");
Ok I will do a little research on `unchecked` I haven't used it yet

2021-09-08 05:57 UTC, Eihcir0 commented on contracts/Vault4.sol
> +        require(_depositEth > 0, "No deposit");
Obviously I'm wrong in my thinking.  I thought maybe if they didnt have any deposit that we could save ourself checking SSTORE?

2021-09-10 16:08 UTC, merged