Exercise6 amm w multicall pattern
devtooligan/yield_mentorship pull request #7
Opened 2021-09-09 01:37 UTC by Eihcir0

Exercise 6 attached.  I went for the bonus.

See AMMRouter.sol which then calls AMMCore.sol

2021-09-09 05:10 UTC, alcueca requested changes
This is a great first attempt at an AMM. The code is super clear, better than my own, and much easier to understand than uniswap.

It's a good time to start looking at gas consumption, avoid any unnecessary storage loads, and any unnecessary calls to other contracts.

2021-09-09 05:10 UTC, alcueca commented on contracts/amm/AMMCore.sol
> +    event Swapped(address guy, address tokenIn, uint256 amountX, uint256 amountY);
Check about the use of `indexed` in events, your frontend engineers will demand some parameters to be indexed so that they can use events efficiently. In here I would index all `address` parameters.

2021-09-09 05:10 UTC, alcueca commented on contracts/amm/AMMCore.sol
> +        x.reserve = x.token.balanceOf(address(this));
You also need to verify that `x.token.balanceOf(address(this))` and `y.token.balanceOf(address(this))` are both greater than zero

2021-09-09 05:10 UTC, alcueca commented on contracts/amm/AMMCore.sol
> +        uint256 added0 = newXreserve - x.reserve;
`addedX`, for consistency.

2021-09-09 05:10 UTC, alcueca commented on contracts/amm/AMMCore.sol
> +        uint256 mintAmount = (((added0 * 1e18) / x.reserve) * k) / 1e18;
This function should be reordered to reduce the chances of shadow under and overflow. As a rule, do all the multiplications first and divisions later, so that you only deal with shadow overflow, and then think on optimizing it.

`uint256 mintAmount = (added0 * k * 1e18) / (x.reserve * 1e18);` -> `= (added0 * k) / x.reserve;` perhaps?

2021-09-09 05:10 UTC, alcueca commented on contracts/amm/AMMCore.sol
> +    function _burnLP(address guy, uint256 wad) external isInitialized isOwner {
`isInitialized` checks that `k > 0`. Below you are also reading the `x` and `y` reserves that must be greater than zero if the AMM was initialized. If you replace `isInitialized` by a `require` on `x.reserve > 0 && y.reserve > 0` you would save a bit of gas.

2021-09-09 05:10 UTC, alcueca commented on contracts/amm/AMMCore.sol
> +        k = x.reserve * y.reserve;
Missing an ` / 1**18`? How was this not picked up in the unit tests?

2021-09-09 05:10 UTC, alcueca commented on contracts/amm/AMMCore.sol
> +        y.token.transfer(guy, yTokensToSend);
Some tokens might not be ERC20 compliant and might fail instead of reverting. It is good practice to use [TransferHelper](https://github.com/yieldprotocol/yield-utils-v2/blob/main/contracts/token/TransferHelper.sol).

2021-09-09 05:10 UTC, alcueca commented on contracts/amm/AMMCore.sol
> +        x.reserve = x.token.balanceOf(address(this));
Aaah, you check that in the router.

While "Fail early" is a great approach in general, data integrity should be verified where it is needed. I would still check that both balances are greater than zero here, instead of on the router.

2021-09-09 05:10 UTC, alcueca commented on contracts/amm/AMMRouter.sol
> +        uint256 reserveY;
You can do `(IERC20 tokenX, uint256 reserveX) = core.x()`, or you can put the `TokenData` struct in its own .sol file and import it from both AMMRouter and AMMCore.

2021-09-09 05:10 UTC, alcueca commented on contracts/amm/AMMRouter.sol
> +import "./AMMCore.sol";
By doing this you are importing the whole bytecode of `AMMCore`, and appending it at the end of `AMMRouter`. You need to create an `IAMMCore.sol` interface file with the function signatures of `AMMCore`.

`AMMCore` inherits from `IAMMCore`, you will need to use the `override` keyword. `AMMRouter` imports `IAMMCore` to know how to use the functions in `AMMCore`

2021-09-09 05:10 UTC, alcueca commented on contracts/amm/AMMRouter.sol
> +    AMMCore public core;
This should be an `IAMMCore` variable.

2021-09-09 05:10 UTC, alcueca commented on contracts/amm/AMMRouter.sol
> +    function mint(uint256 wadX, uint256 wadY) external isInitialized {
`isInitialized` is very expensive here (a CALL to another contract). Do we really need it?

2021-09-09 05:10 UTC, alcueca commented on contracts/amm/AMMCore.sol
> +    function _mintLP(address guy) external isInitialized isOwner {
Do you really need to make all functions `isOwner`?

2021-09-09 05:10 UTC, alcueca commented on contracts/amm/AMMCore.sol
> +    function _init(address admin) external isOwner {
I've also tried to use a preceding underscore to denote permissioned functions, and then two preceding underscores for internal functions. I found that madness lies not far from there.

I would stick to convention and use one preceding underscore for internal functions, and none for permissioned functions.

2021-09-11 04:34 UTC, Eihcir0 commented on contracts/amm/AMMCore.sol
> +    function _init(address admin) external isOwner {
ok great.  I've been trying different things to see what feels right, i would prefer to stick this convention you mentioned

2021-09-11 04:35 UTC, Eihcir0 commented on contracts/amm/AMMCore.sol
> +    function _mintLP(address guy) external isInitialized isOwner {
no i guess i dont'.  i was thinking the router needs to be tighly coupled with the core, but why?  if somebody wanna send tokens in to our contract and call swap then that won't be a problem!

2021-09-11 04:35 UTC, Eihcir0 commented on contracts/amm/AMMRouter.sol
> +    function mint(uint256 wadX, uint256 wadY) external isInitialized {
no we don't need it here!

2021-09-11 04:36 UTC, Eihcir0 commented on contracts/amm/AMMCore.sol
> +        uint256 added0 = newXreserve - x.reserve;
oops, that was a remnant when i was trying something else

2021-09-11 04:36 UTC, Eihcir0 commented on contracts/amm/AMMCore.sol
> +    event Swapped(address guy, address tokenIn, uint256 amountX, uint256 amountY);
ok ill look into that now

2021-09-11 04:38 UTC, Eihcir0 commented on contracts/amm/AMMRouter.sol
> +    AMMCore public core;
Ok great, I'm glad I made this mistake now it's very clear

2021-09-12 02:06 UTC, Eihcir0 commented on contracts/amm/AMMCore.sol
> +        uint256 mintAmount = (((added0 * 1e18) / x.reserve) * k) / 1e18;
got it, multiply first, then divide, then do algebra :)

2021-09-12 02:14 UTC, Eihcir0 commented on contracts/amm/AMMCore.sol
> +        k = x.reserve * y.reserve;
oops, yeah its taken me a minute to get accustomed to wad math.  but i'm feeling good about it now, this won't happen again.

2021-09-12 06:38 UTC, Eihcir0 commented on contracts/amm/AMMRouter.sol
> +        uint256 reserveY;
I ran into some problems with this.  I would definitely prefer to use the TokenData struct over the tuple.

So I moved the struct to it's own file and imported it.  But then I got an error here:
```
Member "x" not found or not visible after argument-dependent lookup in function () view external returns (contract IAMMCore). Did you intend to call the function?
```

So I added `function x() external view returns (TokenData memory);` to the interface, but then I had to update the state variable in AMMCore.sol to this:
```
TokenData public override x;
```

And it gave me an error: `Overriding public state variable return types differ.`

So in the end, the only way I could figure out how to fix this is by explicitly adding a couple getters `getX()` and `getY()`

TBH at this point I think I would have been best nnot using the struct and just leaving in 4 variables:  tokenX, tokenY, reserveX, reserveY.  :/

But I would like to figure out what I did wrong with this one.  Like how can I access a public struct state variable from another contract?

2021-09-12 06:58 UTC, Eihcir0 commented on contracts/interfaces/IAMMCore.sol
> +// SPDX-License-Identifier: MIT
@alcueca please review this interface.  And can you confirm that is a standard pattern to put the events in the Interface?

2021-09-12 20:38 UTC, alcueca requested changes
Great job. Some minor changes requested. You are quite close now to the Uniswap v2 functionality.

2021-09-12 20:38 UTC, alcueca commented on contracts/amm/AMMCore.sol
> +    function getX() external view override returns (TokenData memory) {
Why not making `x` and `y` public and removing the getters?

2021-09-12 20:38 UTC, alcueca commented on contracts/amm/AMMCore.sol
> +        uint256 kValue = k;
Since you are reading `x.reserve` and `y.reserve` to calculate the new `k`, it would be cheaper to deduce that the contract was initialized by requiring that `x.reserve > 0` and `y.reserve > 0`.

2021-09-12 20:38 UTC, alcueca commented on contracts/amm/AMMCore.sol
> +        k = (x.reserve * y.reserve) / 1e18;
Uglier code, but it would be cheaper to do: 
```
xReserve -= xTokensToSend;
yReserve -= yTokensToSend;
x.reserve = xReserve;
y.reserve = yReserve;
k = xReserve * yReserve;
```

The general rule that I follow is that I read once from storage, do everything I need, then I write to storage.

2021-09-12 20:38 UTC, alcueca commented on contracts/amm/AMMRouter.sol
> +        require((x.reserve / y.reserve) * 1e18 == (wadX / wadY) * 1e18, "Invalid amounts");
There are shadow underflows in this formulas, to preserve precision you need to multiply before you divide.

2021-09-12 20:38 UTC, alcueca commented on contracts/interfaces/IAMMCore.sol
> +// SPDX-License-Identifier: MIT
Yeah, all good. I have no opinion on putting the events in the interface or not. You can also put the TokenData struct in the interface, which would be useful since `getX` (or `x`) returns it.

2021-09-12 21:22 UTC, alcueca commented on contracts/amm/AMMRouter.sol
> +        uint256 reserveY;
You put the struct in an library that is used by both contracts. Example:
Data: https://github.com/yieldprotocol/vault-interfaces/blob/main/DataTypes.sol
Usage: https://github.com/yieldprotocol/vault-v2/contracts

2021-09-12 21:22 UTC, alcueca commented on contracts/amm/AMMRouter.sol
> +        uint256 reserveY;
You put the struct in an library that is used by both contracts. Example:
Data: https://github.com/yieldprotocol/vault-interfaces/blob/main/DataTypes.sol
Usage: https://github.com/yieldprotocol/vault-v2/contracts

2021-09-12 21:25 UTC, alcueca commented on contracts/amm/AMMRouter.sol
> +        uint256 reserveY;
You put the struct in an library that is used by both contracts. Example:
Data: https://github.com/yieldprotocol/vault-interfaces/blob/main/DataTypes.sol
Usage: https://github.com/yieldprotocol/vault-v2/tree/master/contracts

Also, you can send and receive structs through ethers https://github.com/yieldprotocol/yield-utils-v2/blob/13ec941f201b0923777771f41de3e72505ef89e8/test/005_timelock.ts#L127

2021-09-13 18:12 UTC, Eihcir0 commented on contracts/amm/AMMCore.sol
> +        uint256 kValue = k;
yeah getting rid of state variable K altogether!

2021-09-13 18:15 UTC, Eihcir0 commented on contracts/amm/AMMRouter.sol
> +        require((x.reserve / y.reserve) * 1e18 == (wadX / wadY) * 1e18, "Invalid amounts");
fixed it

2021-09-13 18:30 UTC, Eihcir0 commented
Hey @alcueca Here is (hopefully final) change for your review.  It's a pretty significant refactor, not only did I remove the "k" variable but I moved some of the logic from the Router to Core so that Router didn't have to read Core state variables.  I also dropped the TokenData struct.  But I think it's very readable now.

One thing that's pretty obvious that I didnt do but that I could do in the future is to just have 1 `swap` method (instead of swapX and swapY).   Maybe put the xToken and yToken (and associted reserves) into an array or maybe even better a mapping.  But I'm kind of ready to start on something else now, and I'm sure you are sick of reviewing it!!

Significant gas savings from first run to now (mostly attributable to losing "K") but also got a big discount on deployment of the router after refactoring.

Original submission:
```
·······························|···························|··············|······························
|  Methods                                                                                              │
··················|············|·············|·············|··············|···············|··············
|  Contract       ·  Method    ·  Min        ·  Max        ·  Avg         ·  # calls      ·  usd (avg)  │
··················|············|·············|·············|··············|···············|··············
|  AMMCore        ·  setOwner  ·          -  ·          -  ·       27018  ·            9  ·          -  │
··················|············|·············|·············|··············|···············|··············
|  AMMRouter      ·  init      ·          -  ·          -  ·      216441  ·            7  ·          -  │
··················|············|·············|·············|··············|···············|··············
|  AMMRouter      ·  mint      ·          -  ·          -  ·      118997  ·            2  ·          -  │
··················|············|·············|·············|··············|···············|··············
|  AMMRouter      ·  sellX     ·          -  ·          -  ·       89423  ·            2  ·          -  │
··················|············|·············|·············|··············|···············|··············
|  AMMRouter      ·  sellY     ·          -  ·          -  ·       84865  ·            2  ·          -  │
··················|············|·············|·············|··············|···············|··············
|  Deployments                 ·                                          ·  % of limit   ·             │
·······························|·············|·············|··············|···············|··············
|  AMMCore                     ·    1447095  ·    1447107  ·     1447104  ·        4.8 %  ·          -  │
·······························|·············|·············|··············|···············|··············
|  AMMRouter                   ·    1116594  ·    1116606  ·     1116605  ·        3.7 %  ·          -  │
·······························|·············|·············|··············|···············|··············

```
Latest submission:
```
······························|···························|··············|······························
|  Methods                                                                                             │
··················|···········|·············|·············|··············|···············|··············
|  Contract       ·  Method   ·  Min        ·  Max        ·  Avg         ·  # calls      ·  usd (avg)  │
··················|···········|·············|·············|··············|···············|··············
|  AMMCore        ·  init     ·          -  ·          -  ·      182603  ·            7  ·          -  │
··················|···········|·············|·············|··············|···············|··············
|  AMMRouter      ·  mint     ·          -  ·          -  ·      110994  ·            2  ·          -  │
··················|···········|·············|·············|··············|···············|··············
|  AMMRouter      ·  sellX    ·          -  ·          -  ·       82633  ·            2  ·          -  │
··················|···········|·············|·············|··············|···············|··············
|  AMMRouter      ·  sellY    ·          -  ·          -  ·       81426  ·            2  ·          -  │
··················|···········|·············|·············|··············|···············|··············
|  Deployments                ·                                          ·  % of limit   ·             │
······························|·············|·············|··············|···············|··············
|  AMMCore                    ·          -  ·          -  ·     1391106  ·        4.6 %  ·          -  │
······························|·············|·············|··············|···············|··············
|  AMMRouter                  ·     564857  ·     564869  ·      564866  ·        1.9 %  ·          -  │

```

2021-09-14 06:00 UTC, alcueca commented
Sounds great, but did you push?

2021-09-14 06:25 UTC, Eihcir0 commented
@alcueca pushed!

2021-09-15 15:29 UTC, alcueca approved these changes
![image](https://user-images.githubusercontent.com/38806121/133463145-8714381b-7047-45cd-9250-74950660cbea.png)

2021-09-15 15:30 UTC, alcueca commented
However, and I hate to be that guy, but have you thought what would happen if you make `reserveX` and `reserveY` two `uint128` packed into a struct?

2021-09-16 20:34 UTC, Eihcir0 commented
> However, and I hate to be that guy, but have you thought what would happen if you make `reserveX` and `reserveY` two `uint128` packed into a struct?

No I haven't really played around with many of the numeric types besides uint128.  That would obv save gas because I could get both reserves for the "price" of one.  And it wouldnt waste any gas because in the case where I only needed one of them, it's still costing me the same.  Good idea!

2021-09-16 22:14 UTC, Eihcir0 commented
> However, and I hate to be that guy, but have you thought what would happen if you make `reserveX` and `reserveY` two `uint128` packed into a struct?

Woah just implemented this, pretty nice gas savings!!

2021-09-16 22:18 UTC, merged