feat(multicollateralvault): code and tests
devtooligan/yield_mentorship pull request #8
Opened 2021-09-17 06:34 UTC by Eihcir0

Multicollateral vault

- Deploy with Dai address
- add token and aggregator contracts with `addAcceptedToken`
- accepts multiple collateral types (all ERC20 tokens)
```
·-----------------------------------------|---------------------------|--------------|-----------------------------·
|           Solc version: 0.8.6           ·  Optimizer enabled: true  ·  Runs: 1000  ·  Block limit: 30000000 gas  │
··········································|···························|··············|······························
|  Methods                                                                                                         │
····························|·············|·············|·············|··············|···············|··············
|  Contract                 ·  Method     ·  Min        ·  Max        ·  Avg         ·  # calls      ·  usd (avg)  │
····························|·············|·············|·············|··············|···············|··············
|  MockPriceFeedAggregator  ·  setRate    ·      23677  ·      26477  ·       25540  ·            3  ·          -  │
····························|·············|·············|·············|··············|···············|··············
|  MultiCollateralVault     ·  borrow     ·      77261  ·     125248  ·      114419  ·           19  ·          -  │
····························|·············|·············|·············|··············|···············|··············
|  MultiCollateralVault     ·  deposit    ·      67261  ·      84373  ·       78819  ·           37  ·          -  │
····························|·············|·············|·············|··············|···············|··············
|  MultiCollateralVault     ·  liquidate  ·      54425  ·      66151  ·       60288  ·            4  ·          -  │
····························|·············|·············|·············|··············|···············|··············
|  MultiCollateralVault     ·  repay      ·          -  ·          -  ·       42245  ·            2  ·          -  │
····························|·············|·············|·············|··············|···············|··············
|  MultiCollateralVault     ·  withdraw   ·      52353  ·      61892  ·       57107  ·            4  ·          -  │
····························|·············|·············|·············|··············|···············|··············
|  Deployments                            ·                                          ·  % of limit   ·             │
··········································|·············|·············|··············|···············|··············
|  MockPriceFeedAggregator                ·     218227  ·     218251  ·      218239  ·        0.7 %  ·          -  │
··········································|·············|·············|··············|···············|··············
|  MultiCollateralVault                   ·    1426383  ·    1426407  ·     1426401  ·        4.8 %  ·          -  │
·-----------------------------------------|-------------|-------------|--------------|---------------|-------------·
```

2021-09-20 06:19 UTC, sblOWPCKCR commented on contracts/MultiCollateralVault.sol
> +        for (uint256 idx = 0; idx < tokensAcceptedArray.length; idx++) {
this will be expensive - the system could have 1000s of tokens, and most users will only have a few collaterals posted. having per-user maps of tokens deposited could help

2021-09-20 06:19 UTC, sblOWPCKCR commented on contracts/MultiCollateralVault.sol
> +        for (uint256 idx = 0; idx < initialTokens.length; idx++) {
weird side effect: if initialTokens/initialFeeds contain duplicates, you overcompute collateral. Maybe not a big deal, but it should be cheap to test for this in the constructor and forget about this detail.

2021-09-20 06:19 UTC, sblOWPCKCR commented on contracts/MultiCollateralVault.sol
> +        return uint256(answer) * 1**(18 - decimals);
does it work if `decimals` is > 18?
also, I think `feed.decimals()` is an external contract call -> expensive. Maybe be cheaper to store cached decimals() in `tokensAcceptedMapping`

2021-09-20 06:19 UTC, sblOWPCKCR commented on contracts/MultiCollateralVault.sol
> +        require(address(IERC20(_token)) == _token, "Not ERC20");
wait, how does this work? I was under impression that you can do `IERC20(x)` on any random address, it doesn't actually check if `x` conforms to IERC20?

2021-09-21 22:36 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +        for (uint256 idx = 0; idx < tokensAcceptedArray.length; idx++) {
got it.  I was thinking there would be only a few tokens lol

2021-09-21 22:39 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +        for (uint256 idx = 0; idx < initialTokens.length; idx++) {
I just decided to do away with this altogether, it wasn't part of the requirements and dont want to blow up the gas cost unnecessarily.  

If I were to do this check I would prob do something like  `mapping(token=>address) memory seen` and skip the token/aggregator if it were already seen

2021-09-21 22:49 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +        return uint256(answer) * 1**(18 - decimals);
decided to keep it in with the price feed mapping

2021-09-21 22:50 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +        require(address(IERC20(_token)) == _token, "Not ERC20");
oops, for some reason I assumed this would work, you know what they say about ASSUME...

2021-09-21 22:50 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +        require(address(IERC20(_token)) == _token, "Not ERC20");
removing this check per our Slack convo

2021-09-22 02:08 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +        return uint256(answer) * 1**(18 - decimals);
also fixed the math throughout

2021-09-22 09:13 UTC, alcueca requested changes
A few code style comments, and one error in the `withdraw` function.

In general, you are ready to work on real life problems and keep on learning there. This is quite a complex assignment, well resolved.

2021-09-22 09:13 UTC, alcueca commented on contracts/MultiCollateralVault.sol
> +    //@dev We are intentionally not removing tokens from this list when balances drop to zero
What would be the cheapest way of removing tokens from the list when balances drop to zero?

2021-09-22 09:13 UTC, alcueca commented on contracts/MultiCollateralVault.sol
> +        require(!tokensAcceptedMapping[_token], "Already added");
I would remove this require, so that you can use this function to change the price feed. Otherwise you are screwed if you ever need to.

2021-09-22 09:13 UTC, alcueca commented on contracts/MultiCollateralVault.sol
> +        emit AddAcceptedToken(_token);
I would emit the address of the price feed as well.

2021-09-22 09:13 UTC, alcueca commented on contracts/MultiCollateralVault.sol
> +    mapping(address => address[]) public tokensDeposited; // user address => array of previously deposited tokens
This can be a `mapping(address => IERC20[])`, it will save you some castings later on.

2021-09-22 09:13 UTC, alcueca commented on contracts/MultiCollateralVault.sol
> +        uint256 oldBalance = deposits[msg.sender][_token];
Not a hard rule, but I follow this naming pattern to make my life easier:
 - internal or private functions preceded by underscore
 - arguments suffixed by underscore when they clash with a state variable, usually needed on constructors, and nowhere else.
 - temporary copies of state variables get the same name as the state variable, suffixed by an underscore.

2021-09-22 09:13 UTC, alcueca commented on contracts/MultiCollateralVault.sol
> +        require((oldBalanceDaiValue - loans[msg.sender]) >= withdrawDaiValue, "Insufficient balance");
I think that you are only considering the deposits of the token being withdrawn, instead of all the deposits from the user. You also need to call `_calculateTotalDepositsDaiValue` on withdrawals.

2021-09-22 09:13 UTC, alcueca commented on contracts/MultiCollateralVault.sol
> +        loans[msg.sender] += _daiWad;
If you surround this by an `unchecked`, could it overflow?

2021-09-22 21:21 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +    //@dev We are intentionally not removing tokens from this list when balances drop to zero
From my research, I would have to basically create a new array in memory, iterate through the array in state, adding each to the new array except for the one being removied.  Then I would overwrite the state variable with the memory one.  Is this correct?

Another way, maybe just overwrite the index with a Zero instead of actually removing it from the list, then when iterating through the list just skip those with zero, but without spending some time gas golfing I'm not sure if this would be a significant savings.

2021-09-22 21:23 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +        require(!tokensAcceptedMapping[_token], "Already added");
doh!  good point

2021-09-22 21:34 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +        require(!tokensAcceptedMapping[_token], "Already added");
also renaming this fn to 'setAcceptedToken'

2021-09-22 21:35 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +        uint256 oldBalance = deposits[msg.sender][_token];
Great thanks for letting me know, I would like to adopt this pattern as well

2021-09-22 21:54 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +        require((oldBalanceDaiValue - loans[msg.sender]) >= withdrawDaiValue, "Insufficient balance");
good catch.  This was a remnant of the single collateral vault I copy pasta'd and somehow fell through the cracks in the tests.  Updating test for this as well.

2021-09-22 22:37 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +        loans[msg.sender] += _daiWad;
no it could not thanks to the require on the previous line. updating now

2021-09-22 22:45 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +    mapping(address => address[]) public tokensDeposited; // user address => array of previously deposited tokens
Oh nice I always wondered about that but kept forgetting to gas golf it

2021-09-22 23:05 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +    mapping(address => address[]) public tokensDeposited; // user address => array of previously deposited tokens
hmm I just switched this to IERC20[] and then updated the codebase accordingly and when i reran the gas it was exactly the same?  And also I had to pull the address out of the token whenever I needed it, for example, to look up a user deposit so it didnt seem to really  up the codebase much either.  The way the code is right now, the only times I have to cast IERC20 is when Im dealing with an address passed in by user (deposit, withdraw) so this didn't help me there.

Not sure if I'm missing something, but I'm skipping this suggestion now.

2021-09-22 23:18 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +        unchecked {
@alcueca I found a couple more places I can use unchecked, I think this one is a candidate because we are guaranteed that the wad > 0 and rate > 0.

2021-09-23 11:48 UTC, alcueca commented on contracts/MultiCollateralVault.sol
> +    mapping(address => address[]) public tokensDeposited; // user address => array of previously deposited tokens
Using `IERC20` instead of `address` doesn't do anything on gas, the resulting bytecode is the same. The solidity code is cleaner, though, because you don't have to cast `IERC20(foo)` later on. You can also use `IERC20` as a parameter `foo(IERC20 bar)` and the compiler does the castings for you.

2021-09-23 11:50 UTC, alcueca commented on contracts/MultiCollateralVault.sol
> +        loans[msg.sender] += _daiWad;
Even without the `require` it wouldn't overflow, can you guess why?

2021-09-23 11:53 UTC, alcueca commented on contracts/MultiCollateralVault.sol
> +    //@dev We are intentionally not removing tokens from this list when balances drop to zero
There is a third way, which is to replace in the array the address of the token whose balance when to zero with the last token in the array, and then delete the last element of the array. It would be two SSTORE.

[foo, bar, baz, wow] -> [foo, _, baz, wow] -> [foo, wow, baz, wow] -> [foo, wow, baz]

2021-09-23 11:57 UTC, alcueca commented on contracts/MultiCollateralVault.sol
> +        unchecked {
`wad * 10**decimals` can easily overflow, though.

2021-09-23 14:59 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +    //@dev We are intentionally not removing tokens from this list when balances drop to zero
Oh yeah.  I started to think down this path but then immediately thought it would cost too much.  But I see clearly now that array[idx] = array.pop() works nicely...I will implement this now

2021-09-23 15:34 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +    //@dev We are intentionally not removing tokens from this list when balances drop to zero
oh nice, and if we take care of the remove from array part, then we can just use array.push() to add the new tokens.

this was a great exercise, thanks for pushing me to think about it

2021-09-23 17:12 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +    //@dev We are intentionally not removing tokens from this list when balances drop to zero
added test assertions as well

2021-09-23 17:18 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +    mapping(address => address[]) public tokensDeposited; // user address => array of previously deposited tokens
^^ Oh ok, I understand.  ` You can also use IERC20 as a parameter foo(IERC20 bar)` thats the part I was missing

2021-09-23 17:19 UTC, Eihcir0 commented on contracts/MultiCollateralVault.sol
> +        unchecked {
why yes it absolutely does, I must've been really tired when I was looking at this last night... sorry

2021-09-23 22:59 UTC, merged